version: '3.8'

services:
  cosmic-jwt-issuer-mock:
    container_name: cosmic-jwt-issuer-mock
    build:
      context: ./jwt-issuer-mock
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/__admin/requests || exit 1" ]
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 3
    ports:
      - "8083:8080"